#-------------------------------
# General Site Settings

title: Sporadic Creativity
description: Artist // Engineer // Self-Learner
email: sporadicreativity@gmail.com

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: About Me, url: '#about-me'}
- {name: Work, url: '#work'}
- {name: Contact, url: '#contact'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Art website by Raksha Jain'
  rel-author: 'https://plus.google.com/u/2/101957495897194089403'
  rel-publisher: 'https://plus.google.com/u/2/101957495897194089403'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

blurb: >
  I love discovering shades. Bright and dull, dark and light, vibrant and dead, every tinch of color has its own place in a palette. Its funny how they compete to get on the canvas.
  I am an *engineering student*, given my love for science. My *passion for fine arts* makes the whole process of learning so much more creative, helping me to think out of the box.<br />**Its aptly said: where Science ends, Art begins.**

#-------------------------------
# Work Section

projects:
- {name: TYPO International Design Talks, folder: 'proj-1', file: 'work/proj-1.html'}
- {name: City-IN website concept, folder: 'proj-2', file: 'work/proj-2.html'}
- {name: Crispy Icons, folder: 'proj-3', file: 'work/proj-3.html'}
- {name: Flat Mobile UI/UX Concept, folder: 'proj-4', file: 'work/proj-4.html'}
- {name: Fresh It Up, folder: 'proj-5', file: 'work/proj-5.html'}
- {name: Timeline Page, folder: 'proj-6', file: 'work/proj-6.html'}
- {name: Weather Dashboard, folder: 'proj-7', file: 'work/proj-7.html'}
- {name: Stripes & Co, folder: 'proj-8', file: 'work/proj-8.html'}




# Contact Section

social:
- {icon: 'twitter', link: 'https://twitter.com/raksha1302'}
- {icon: 'facebook', link: 'https://www.facebook.com/raksha.jain.167'}
- {icon: 'instagram', link: 'https://www.instagram.com/rakshajain13/'}
- {icon: 'google-plus', link: 'https://plus.google.com/u/2/101957495897194089403'}
- {icon: 'linkedin', link: ''}
- {icon: 'github', link: 'https://github.com/Sporadicreativity'}



# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
